import genanki

# Expressions espagnoles avec traduction en français
spanish_expressions = [
    ("A duras penas", "À grand-peine, avec difficulté"),
    ("A pesar de", "Malgré"),
    ("A propósito", "À propos, d'ailleurs"),
    ("A regañadientes", "À contrecœur"),
    ("A lo mejor", "Probablement, peut-être"),
    ("A fin de cuentas", "En fin de compte"),
    ("Echar de menos", "Manquer à, regretter"),
    ("Estar a dos velas", "Être fauché (sans un sou)"),
    ("Estar en las nubes", "Être dans la lune"),
    ("Estar como una cabra", "Être fou/folle (comme une chèvre)"),
    ("Costar un ojo de la cara", "Coûter les yeux de la tête"),
    ("De tal palo, tal astilla", "Tel père, tel fils (la pomme ne tombe jamais loin de l'arbre)"),
    ("No hay mal que por bien no venga", "À quelque chose malheur est bon"),
    ("Más vale tarde que nunca", "Mieux vaut tard que jamais"),
    ("Querer es poder", "Quand on veut, on peut"),
    ("Camarón que se duerme, se lo lleva la corriente", "Celui qui s'endort se fait emporter par le courant"),
    ("Al que madruga, Dios le ayuda", "L'avenir appartient à ceux qui se lèvent tôt"),
    ("Perro ladrador, poco mordedor", "Chien qui aboie ne mord pas"),
    ("En boca cerrada no entran moscas", "Mieux vaut se taire (bouche fermée, pas de mouches)"),
    ("No es oro todo lo que reluce", "Tout ce qui brille n'est pas or"),
    ("Dime con quién andas y te diré quién eres", "Dis-moi qui tu fréquentes, je te dirai qui tu es"),
    ("Borra y va de nuevo", "On efface tout et on recommence"),
    ("Cada dos por tres", "Très souvent, fréquemment"),
    ("Caer en gracia", "Plaire à, être apprécié par"),
    ("Caérsele el alma a los pies", "Avoir le moral à zéro"),
    ("Consultar con la almohada", "La nuit porte conseil"),
    ("Dar la lata", "Embêter, importuner"),
    ("Dar en el clavo", "Taper dans le mille"),
    ("De buena gana", "Volontiers"),
    ("De punta en blanco", "Sur son trente-et-un"),
    ("Echar leña al fuego", "Jeter de l'huile sur le feu"),
    ("El mundo es un pañuelo", "Le monde est petit"),
    ("En un abrir y cerrar de ojos", "En un clin d'œil"),
    ("Ir al grano", "Aller droit au but"),
    ("Matar dos pájaros de un tiro", "Faire d'une pierre deux coups"),
    ("Más claro, agua", "C'est clair comme de l'eau de roche"),
    ("Meter la pata", "Mettre les pieds dans le plat"),
    ("Ni fu ni fa", "Ni bien ni mal, bof"),
    ("No tener pelos en la lengua", "Ne pas avoir sa langue dans sa poche"),
    ("Pasar la noche en blanco", "Passer une nuit blanche"),
    ("Ponerse las pilas", "Se mettre au travail, se bouger"),
    ("Por si las moscas", "Au cas où"),
    ("Romper el hielo", "Rompre la glace"),
    ("Ser pan comido", "Être du gâteau, être très facile"),
    ("Tener buena cara", "Avoir bonne mine"),
    ("Tener mala pata", "Avoir de la malchance"),
    ("Tomar el pelo", "Faire marcher (quelqu'un), se moquer"),
    ("Ver las estrellas", "Voir 36 chandelles"),
    ("Andar con ojo", "Faire attention"),
    ("Cortar por lo sano", "Couper court, prendre une décision radicale"),
    ("Cruzarse de brazos", "Rester les bras croisés"),
    ("Dar por sentado", "Tenir pour acquis"),
    ("Echar un cable", "Donner un coup de main"),
    ("Hacer la vista gorda", "Fermer les yeux (sur quelque chose)"),
    ("Importar un pimiento", "S'en ficher complètement"),
    ("Meterse en camisa de once varas", "Se fourrer dans un sale drap"),
    ("No tener ni pies ni cabeza", "Ne pas avoir ni queue ni tête"),
    ("Poner los puntos sobre las íes", "Mettre les points sur les i"),
    ("Quedarse en blanco", "Avoir un trou de mémoire"),
    ("Sacar de quicio", "Faire sortir de ses gonds"),
    ("Ser un cero a la izquierda", "Être un bon à rien"),
    ("Tener la sartén por el mango", "Avoir le couteau dans le beurre"),
    ("Tirar la casa por la ventana", "Jeter l'argent par les fenêtres"),
    ("Tomar cartas en el asunto", "Prendre les choses en main"),
    ("Volver a las andadas", "Retomber dans ses travers"),
    ("A capa y espada", "Avec acharnement, bec et ongles"),
    ("A pedir de boca", "À souhait, comme sur des roulettes"),
    ("Ahogarse en un vaso de agua", "Se noyer dans un verre d'eau"),
    ("Buscarle tres pies al gato", "Chercher la petite bête"),
    ("Caerse del guindo", "Tomber des nues"),
    ("Con las manos en la masa", "La main dans le sac"),
    ("Darle la espalda", "Tourner le dos à"),
    ("Estar entre la espada y la pared", "Être entre l'arbre et l'écorce"),
    ("Hacer de tripas corazón", "Faire bonne figure"),
    ("Irse por las ramas", "Partir dans tous les sens"),
    ("Llevarse un chasco", "Être déçu"),
    ("No dar el brazo a torcer", "Ne pas plier, ne pas céder"),
    ("Pagar los platos rotos", "Payer les pots cassés"),
    ("Poner el grito en el cielo", "Crier au scandale"),
    ("Quien mucho abarca, poco aprieta", "Qui trop embrasse mal étreint"),
    ("Saber al dedillo", "Connaître sur le bout des doigts"),
    ("Ser uña y carne", "Être comme les deux doigts de la main"),
    ("Tirar la toalla", "Jeter l'éponge"),
    ("Tomar el toro por los cuernos", "Prendre le taureau par les cornes"),
    ("Zapatero a tus zapatos", "À chacun son métier"),
    ("A trancas y barrancas", "Tant bien que mal, cahin-caha"),
    ("Bajar la guardia", "Baisser la garde"),
    ("Caer en saco roto", "Tomber dans l'oreille d'un sourd"),
    ("Echar balones fuera", "Éluder la question, botter en touche"),
    ("Hacer mutis por el foro", "S'éclipser discrètement"),
    ("Irse al garete", "Partir à vau-l'eau"),
    ("No estar el horno para bollos", "Ce n'est pas le moment"),
    ("Ponerse morado/a", "Se goinfrer, manger à s'en rendre malade"),
    ("Ser del año de la pera", "Dater de Mathusalem"),
    ("Tener la mosca detrás de la oreja", "Avoir la puce à l'oreille"),
    ("Vender humo", "Vendre du vent, faire des promesses en l'air"),
    ("No tener dos dedos de frente", "Ne pas avoir deux sous de bon sens"),
    ("Estar con el agua al cuello", "Avoir l'eau jusqu'au cou"),
    ("Más vale pájaro en mano que ciento volando", "Un tiens vaut mieux que deux tu l'auras"),
    ("A lo hecho, pecho", "Ce qui est fait est fait"),
    ("Poner toda la carne en el asador", "Mettre tous ses atouts dans la balance"),
    ("Quien siembra vientos, recoge tempestades", "Qui sème le vent récolte la tempête"),
    ("Se me fue el santo al cielo", "J'ai oublié ce que j'allais dire"),
    ("Una de cal y otra de arena", "Un coup de chaud, un coup de froid"),
    ("De perdidos al río", "Tant qu'à faire"),
    ("Estar en su salsa", "Être dans son élément"),
    ("Hablar por los codos", "Parler sans arrêt"),
    ("Meter baza", "Mettre son grain de sel"),
    ("No hay moros en la costa", "Il n'y a pas de danger"),
    ("Ser más listo que el hambre", "Être plus malin que la faim"),
    ("Tener un humor de perros", "Avoir un sale caractère"),
    ("Estar como pez en el agua", "Être comme un poisson dans l'eau"),
    ("Poner la mano en el fuego", "Mettre sa main au feu"),
    ("Salvarse por los pelos", "S'en sortir de justesse"),
    ("Ser un ratón de biblioteca", "Être un rat de bibliothèque"),
    ("Tener un as en la manga", "Avoir un as dans sa manche"),
    ("Pasar por el aro", "Se plier aux règles"),
    ("No dar pie con bola", "Ne pas en rater une"),
    ("Con pelos y señales", "Avec force détails"),
    ("El que ríe último, ríe mejor", "Qui rit le dernier, rit le mieux"),
    ("A ojo de buen cubero", "À vue de nez"),
    ("En menos que canta un gallo", "En un clin d'œil"),
    ("Buscar una aguja en un pajar", "Chercher une aiguille dans une botte de foin"),
    ("Cruzársele los cables", "Péter les plombs"),
    ("Dar con la horma de su zapato", "Trouver chaussure à son pied"),
    ("Echar una mano", "Donner un coup de main"),
    ("No tener ni un duro", "Ne pas avoir un sou"),
    ("Poner los cuernos", "Tromper son/sa partenaire"),
    ("Ser un trozo de pan", "Être une crème (un morceau de pain)"),
    ("Tener pájaros en la cabeza", "Avoir des idées folles"),
]

# Modèle de note Anki
model = genanki.Model(
    1607392319,
    "Expressions espagnoles - Français",
    fields=[
        {"name": "Espagnol"},
        {"name": "Français"},
    ],
    templates=[{
        "name": "Carte 1",
        "qfmt": "<div style='font-size: 28px; text-align: center; padding: 40px;'><b>{{Espagnol}}</b></div>",
        "afmt": "<div style='font-size: 28px; text-align: center; padding: 40px;'><b>{{Espagnol}}</b><br><br><hr><br><span style='font-size: 24px; color: #2e7d32;'>{{Français}}</span></div>",
    }],
    css=".card { font-family: 'Segoe UI', Arial, sans-serif; background-color: #fafafa; }"
)

# Créer le paquet
deck = genanki.Deck(2059400110, "Expressions espagnoles")

for esp, fra in spanish_expressions:
    note = genanki.Note(model=model, fields=[esp, fra])
    deck.add_note(note)

# Exporter en .apkg
output_path = "expressions_espagnoles.apkg"
genanki.Package(deck).write_to_file(output_path)

print(f"✅ Paquet Anki créé avec succès : {output_path}")
print(f"   Nombre de cartes : {len(spanish_expressions)}")