import genanki

# Portuguese expressions with French translations
portuguese_expressions = [
    ("Água mole em pedra dura tanto bate até que fura.", "À force de persévérance, on finit par réussir (L'eau douce sur la pierre dure frappe tant qu'elle perce)."),
    ("Cada macaco no seu galho.", "Chacun à sa place (Chaque singe sur sa branche)."),
    ("De grão em grão, a galinha enche o papo.", "Petit à petit l'oiseau fait son nid (De grain en grain, la poule remplit son jabot)."),
    ("Devagar se vai ao longe.", "Doucement mais sûrement (Lentement on va loin)."),
    ("Em casa de ferreiro, espeto de pau.", "Les cordonniers sont toujours les plus mal chaussés (Chez le forgeron, broche en bois)."),
    ("Falar é fácil, fazer é que é difícil.", "C'est plus facile à dire qu'à faire (Parler est facile, faire est difficile)."),
    ("Não deixes para amanhã o que podes fazer hoje.", "Ne remets pas à demain ce que tu peux faire aujourd'hui."),
    ("Mais vale um pássaro na mão do que dois a voar.", "Un tiens vaut mieux que deux tu l'auras (Mieux vaut un oiseau dans la main que deux à voler)."),
    ("Onde há fumaça, há fogo.", "Il n'y a pas de fumée sans feu (Où il y a de la fumée, il y a du feu)."),
    ("Quem não arrisca não petisca.", "Qui ne tente rien n'a rien (Qui ne risque pas ne grignote pas)."),
    ("Quem procura, acha.", "Qui cherche trouve."),
    ("Quem ri por último, ri melhor.", "Qui rit le dernier, rit le mieux."),
    ("Quem semeia ventos, colhe tempestades.", "Qui sème le vent récolte la tempête."),
    ("Saco vazio não para em pé.", "Un ventre vide ne tient pas debout."),
    ("Tudo o que sobe, desce.", "Tout ce qui monte doit redescendre."),
    ("Uma andorinha só não faz verão.", "Une hirondelle ne fait pas le printemps (Une hirondelle seule ne fait pas l'été)."),
    ("É dando que se recebe.", "C'est en donnant qu'on reçoit."),
    ("Sem querer querendo.", "Sans le vouloir en le voulant (par accident, mais avec un sous-entendu de volontaire)."),
    ("Pau para toda obra.", "Bon à tout faire (Bâton pour tout travail)."),
    ("Bater as botas.", "Casser sa pipe (Frapper les bottes)."),
    ("Com a faca e o queijo na mão.", "Avoir toutes les cartes en main (Avec le couteau et le fromage à la main)."),
    ("Dar com a língua nos dentes.", "Vendre la mèche (Donner avec la langue sur les dents)."),
    ("Dar uma mãozinha.", "Donner un coup de main."),
    ("Estar com a pulga atrás da orelha.", "Avoir la puce à l'oreille."),
    ("Ficar de olho.", "Garder un œil."),
    ("Ir direto ao ponto.", "Aller droit au but."),
    ("Lavar as mãos.", "S'en laver les mains."),
    ("Meter os pés pelas mãos.", "Mettre les pieds dans le plat."),
    ("Não ter papas na língua.", "Ne pas avoir sa langue dans sa poche."),
    ("Pão pão, queijo queijo.", "Appeler un chat un chat (Pain pain, fromage fromage)."),
    ("Perder a cabeça.", "Perdre la tête."),
    ("Pisar na bola.", "Faire une gaffe (Marcher sur le ballon)."),
    ("Pôr a mão no fogo.", "Mettre sa main au feu."),
    ("Quebrar o galho.", "Dépanner (Casser la branche)."),
    ("Rodar a baiana.", "Faire un scandale (Faire tourner la Bahianaise)."),
    ("Sair pela culatra.", "Tourner au vinaigre (Sortir par la culasse)."),
    ("Sem eira nem beira.", "Sans le sou (Sans toiture ni bordure)."),
    ("Ser farinha do mesmo saco.", "Être du même acabit (Être de la farine du même sac)."),
    ("Tirar o chapéu.", "Tirer son chapeau."),
    ("Trocar as bolas.", "Mélanger les pinceaux (Échanger les balles)."),
    ("Virar a casaca.", "Retourner sa veste (Tourner la veste)."),
    ("À toa.", "Au hasard, inutilement."),
    ("À beça.", "En abondance."),
    ("À flor da pele.", "À fleur de peau."),
    ("Bater um papo.", "Bavarder."),
    ("Cair em si.", "Reprendre ses esprits."),
    ("Custo a crer.", "J'ai du mal à y croire."),
    ("Dar um bolo.", "Poser un lapin."),
    ("De cara.", "De face, directement."),
    ("De repente.", "Soudainement."),
    ("Encher linguiça.", "Remplir la saucisse (raconter des choses sans intérêt)."),
    ("Ficar de cara.", "Être choqué."),
    ("Ficar por dentro.", "Être au courant."),
    ("Fora de mão.", "Pas pratique (loin de la main)."),
    ("Ir com a cara.", "Aimer, apprécier."),
    ("Ir de vento em popa.", "Voguer à pleines voiles, aller très bien."),
    ("Levar a sério.", "Prendre au sérieux."),
    ("Mão de vaca.", "Radin (Main de vache)."),
    ("Morrer de rir.", "Mourir de rire."),
    ("Nem a pau.", "Même pas en rêve (Même pas avec un bâton)."),
    ("No fim das contas.", "Au final, en fin de compte."),
    ("Pagar o pato.", "Payer les pots cassés."),
    ("Pelo visto.", "Apparemment."),
    ("Pisar na jaca.", "Faire une gaffe (Marcher sur le jacquier)."),
    ("Por via das dúvidas.", "Pour lever le doute, au cas où."),
    ("Procurar agulha no palheiro.", "Chercher une aiguille dans une botte de foin."),
    ("Quebrar um galho.", "Dépanner."),
    ("Rir à toa.", "Rire sans raison."),
    ("Sair do sério.", "Sortir de ses gonds."),
    ("Sem mais nem menos.", "Sans crier gare."),
    ("Ser uma mão na roda.", "Être très utile (Être une main sur la roue)."),
    ("Ter o rei na barriga.", "Avoir la grosse tête (Avoir le roi dans le ventre)."),
    ("Tocar o terror.", "Semer la terreur."),
    ("Tomar as rédeas.", "Prendre les rênes."),
    ("Trocar seis por meia dúzia.", "Changer six pour une demi-douzaine (changer sans rien changer)."),
    ("Virar a mesa.", "Renverser la table."),
    ("Comer com os olhos.", "Manger des yeux."),
    ("Encaixar como uma luva.", "Aller comme un gant."),
    ("Enrolar o cabo.", "Traîner des pieds (Enrouler le câble)."),
    ("Estar com a corda no pescoço.", "Avoir la corde au cou."),
    ("Fazer das tripas coração.", "Faire bonne figure (Faire des tripes un cœur)."),
    ("Ficar de boca aberta.", "Rester bouche bée."),
    ("Levar um fora.", "Se faire larguer (Recevoir un dehors)."),
    ("Mudar da água para o vinho.", "Changer du tout au tout (Changer de l'eau au vin)."),
    ("Não ter onde cair morto.", "Ne pas avoir un sou (Ne pas avoir où tomber mort)."),
    ("Pelo sim, pelo não.", "Au cas où (Pour le oui, pour le non)."),
    ("Pôr os pingos nos is.", "Mettre les points sur les i."),
    ("Ter estômago para algo.", "Avoir le courage de faire quelque chose (Avoir l'estomac pour quelque chose)."),
    ("Bateu as botas", "Il est mort."),
    ("Cair do cavalo", "Tomber de haut."),
    ("Fazer vista grossa", "Fermer les yeux (sur quelque chose)."),
    ("Levar um choque", "Avoir un choc."),
    ("Cair por terra", "Tomber à l'eau (un projet)."),
    ("Comer bola", "Faire une erreur (Manger le ballon)."),
    ("Dar no pé", "S'enfuir."),
    ("Dar um jeitinho", "Trouver un petit arrangement."),
    ("Ficar de olho", "Garder un œil."),
    ("Ir com os bois", "Aller avec les bœufs (suivre la masse)."),
    ("Largar o osso", "Lâcher l'affaire (Lâcher l'os)."),
    ("Puxar o saco", "Flatter (Tirer le sac)."),
    ("Tirar sarro", "Se moquer."),
    ("Acabar em pizza", "Finir en eau de boudin (Finir en pizza, expression brésilienne)."),
    ("Bater na madeira", "Toucher du bois."),
    ("Cair nas graças", "Entrer dans les bonnes grâces."),
    ("Fazer das tripas coração", "Faire bonne figure."),
    ("Ficar para titia", "Rester vieille fille."),
    ("Ir para a cucuia", "Aller se faire voir (Aller au cucuia)."),
    ("Jogar a toalha", "Jeter l'éponge."),
    ("Dar a volta por cima", "Prendre le dessus."),
]

# Anki model
model = genanki.Model(
    1607392321, # Unique ID for this model
    "Expressions portugaises - Français",
    fields=[{"name": "Portugais"}, {"name": "Français"}],
    templates=[{
        "name": "Carte 1",
        "qfmt": "<div style='font-size:28px; text-align:center; padding:40px;'><b>{{Portugais}}</b></div>",
        "afmt": "<div style='font-size:28px; text-align:center; padding:40px;'><b>{{Portugais}}</b><br><br><hr><br><span style='font-size:24px; color:#2e7d32;'>{{Français}}</span></div>",
    }],
    css=".card {font-family: 'Segoe UI', Arial, sans-serif; background-color:#fafafa;}"
)

# Create a new deck
deck = genanki.Deck(2059400112, "Expressions portugaises") # Unique ID for this deck

# Add notes to the deck
for pt, fra in portuguese_expressions:
    note = genanki.Note(model=model, fields=[pt, fra])
    deck.add_note(note)

# Export to .apkg
output_path = "expressions_portugaises.apkg"
genanki.Package(deck).write_to_file(output_path)

print(f"✅ Paquet Anki créé avec succès : {output_path} ({len(portuguese_expressions)} cartes)")
