import genanki

# English expressions with French translations
english_expressions = [
    ("Break the ice", "Briser la glace"),
    ("A piece of cake", "C'est du gâteau"),
    ("Better late than never", "Mieux vaut tard que jamais"),
    ("Bite the bullet", "Prendre son courage à deux mains"),
    ("Hit the sack", "Aller au lit"),
    ("Let the cat out of the bag", "Vendre la mèche"),
    ("Once in a blue moon", "Tous les trente-six du mois"),
    ("Speak of the devil", "Quand on parle du loup"),
    ("Under the weather", "Ne pas être dans son assiette"),
    ("When pigs fly", "Quand les poules auront des dents"),
    ("Cost an arm and a leg", "Coûter les yeux de la tête"),
    ("Hit the nail on the head", "Mettre dans le mille"),
    ("Kill two birds with one stone", "Faire d'une pierre deux coups"),
    ("Let sleeping dogs lie", "Il ne faut pas réveiller le chat qui dort"),
    ("The ball is in your court", "La balle est dans votre camp"),
    ("Burn the midnight oil", "Brûler la chandelle par les deux bouts"),
    ("Cry over spilled milk", "Pleurer sur le lait renversé"),
    ("Don’t count your chickens before they hatch", "Il ne faut pas vendre la peau de l'ours avant de l'avoir tué"),
    ("Every cloud has a silver lining", "À quelque chose malheur est bon"),
    ("Fit as a fiddle", "En pleine forme"),
    ("Give someone the cold shoulder", "Faire la tête à quelqu'un"),
    ("Hit the road", "Prendre la route"),
    ("In hot water", "Être dans de beaux draps"),
    ("It’s a small world", "Le monde est petit"),
    ("Jump on the bandwagon", "Suivre le mouvement"),
    ("Keep your fingers crossed", "Croiser les doigts"),
    ("Leave no stone unturned", "Ne laisser aucune pierre non retournée"),
    ("Let the chips fall where they may", "Laisser les choses suivre leur cours"),
    ("Make a long story short", "Pour faire court"),
    ("No pain, no gain", "On n’a rien sans rien"),
    ("On cloud nine", "Être sur un petit nuage"),
    ("Out of the blue", "Sorti de nulle part"),
    ("Play it by ear", "Faire au fur et à mesure"),
    ("Pull someone’s leg", "Faire marcher quelqu'un"),
    ("Rain on someone’s parade", "Faire la pluie et le beau temps"),
    ("Read between the lines", "Lire entre les lignes"),
    ("Sit on the fence", "Être indécis"),
    ("Take it with a grain of salt", "Prendre avec des pincettes"),
    ("The best of both worlds", "Le meilleur des deux mondes"),
    ("The early bird catches the worm", "Le monde appartient à ceux qui se lèvent tôt"),
    ("The tip of the iceberg", "La partie émergée de l'iceberg"),
    ("Throw in the towel", "Jeter l'éponge"),
    ("Turn a blind eye", "Fermer les yeux"),
    ("Under your nose", "Sous votre nez"),
    ("You can’t judge a book by its cover", "Il ne faut pas juger un livre à sa couverture"),
    ("A blessing in disguise", "Un mal pour un bien"),
    ("A dime a dozen", "À la pelle"),
    ("Add insult to injury", "Enfoncer le clou"),
    ("Bark up the wrong tree", "Faire fausse route"),
    ("Beat around the bush", "Tourner autour du pot"),
    ("Bite off more than you can chew", "Avoir les yeux plus gros que le ventre"),
    ("Break a leg", "Bonne chance"),
    ("By the skin of your teeth", "De justesse"),
    ("Caught red-handed", "Pris sur le fait"),
    ("Cold feet", "Avoir les jetons"),
    ("Don’t bite the hand that feeds you", "Ne mordez pas la main qui vous nourrit"),
    ("Don’t put all your eggs in one basket", "Ne mettez pas tous vos œufs dans le même panier"),
    ("Feel under the weather", "Ne pas être dans son assiette"),
    ("Give the benefit of the doubt", "Accorder le bénéfice du doute"),
    ("Hit the jackpot", "Toucher le jackpot"),
    ("In the nick of time", "Juste à temps"),
    ("It takes two to tango", "Il faut être deux pour danser le tango"),
    ("Jump the gun", "Brûler les étapes"),
    ("Keep your chin up", "Restez optimiste"),
    ("Last but not least", "Enfin mais pas des moindres"),
    ("Let sleeping dogs lie", "Il ne faut pas réveiller le chat qui dort"),
    ("Make a mountain out of a molehill", "Faire d'une mouche un éléphant"),
    ("Miss the boat", "Manquer le coche"),
    ("No strings attached", "Sans condition"),
    ("On the ball", "Être dans le coup"),
    ("Out of the frying pan into the fire", "D'une poêle à frire dans le feu"),
    ("Pull yourself together", "Reprendre ses esprits"),
    ("Put your money where your mouth is", "Mettre son argent où est sa bouche"),
    ("Raining cats and dogs", "Il pleut des cordes"),
    ("Saved by the bell", "Sauvé in extremis"),
    ("Spill the beans", "Vendre la mèche"),
    ("Take the bull by the horns", "Prendre le taureau par les cornes"),
    ("The ball is in your court", "La balle est dans votre camp"),
    ("The last straw", "La goutte d'eau qui fait déborder le vase"),
    ("Through thick and thin", "Dans les bons comme les mauvais moments"),
    ("Turn over a new leaf", "Tourner une nouvelle page"),
    ("Up in the air", "En suspens"),
    ("You can’t have your cake and eat it too", "On ne peut pas avoir le beurre et l'argent du beurre"),
    ("Your guess is as good as mine", "Je n'en sais rien plus que vous"),
    ("A bird in the hand is worth two in the bush", "Un tiens vaut mieux que deux tu l'auras"),
    ("A leopard can’t change its spots", "Chassez le naturel, il revient au galop"),
    ("All in the same boat", "Tous dans le même bateau"),
    ("Bite the dust", "Mourir"),
    ("Cross that bridge when you come to it", "On verra quand on y sera"),
    ("Don’t judge a book by its cover", "Il ne faut pas juger un livre à sa couverture"),
    ("Every dog has its day", "Chacun son heure de gloire"),
    ("Give someone the benefit of the doubt", "Accorder le bénéfice du doute"),
    ("In the heat of the moment", "Dans le feu de l'action"),
    ("It’s not rocket science", "Ce n’est pas sorcier"),
    ("Let the cat out of the bag", "Vendre la mèche"),
    ("No use crying over spilt milk", "Il ne sert à rien de pleurer sur le lait renversé"),
    ("On cloud nine", "Être sur un petit nuage"),
    ("Out of sight, out of mind", "Loin des yeux, loin du cœur"),
    ("Practice makes perfect", "C’est en forgeant qu’on devient forgeron"),
    ("The early bird catches the worm", "Le monde appartient à ceux qui se lèvent tôt"),
    ("The sky’s the limit", "Le ciel est la limite"),
    ("When the going gets tough, the tough get going", "Quand le jeu devient dur, les durs s’y mettent"),
    ("You scratch my back and I’ll scratch yours", "Je te rends la pareille"),
]

# Modèle de note Anki
model = genanki.Model(
    1607392320,
    "Expressions anglaises - Français",
    fields=[{"name": "Anglais"}, {"name": "Français"}],
    templates=[{
        "name": "Carte 1",
        "qfmt": "<div style='font-size:28px; text-align:center; padding:40px;'><b>{{Anglais}}</b></div>",
        "afmt": "<div style='font-size:28px; text-align:center; padding:40px;'><b>{{Anglais}}</b><br><br><hr><br><span style='font-size:24px; color:#2e7d32;'>{{Français}}</span></div>",
    }],
    css=".card {font-family: 'Segoe UI', Arial, sans-serif; background-color:#fafafa;}"
)

deck = genanki.Deck(2059400111, "Expressions anglaises")
for eng, fra in english_expressions:
    note = genanki.Note(model=model, fields=[eng, fra])
    deck.add_note(note)

output_path = "expressions_anglais.apkg"
genanki.Package(deck).write_to_file(output_path)
print(f"✅ Paquet Anki créé : {output_path} ({len(english_expressions)} cartes)")
